package de.htwg.se.thirtyone.model

case class Deck(size: Int = 10) {
  def deck = Vector[Card]  (
    //diamonds
    Card('♦', "2", size),
    Card('♦', "3", size),
    Card('♦', "4", size),
    Card('♦', "5", size),
    Card('♦', "6", size),
    Card('♦', "7", size),
    Card('♦', "8", size),
    Card('♦', "9", size),
    Card('♦', "10", size),
    Card('♦', "J", size),
    Card('♦', "Q", size),
    Card('♦', "K", size),
    Card('♦', "A", size),
    //spades
    Card('♠', "2", size),
    Card('♠', "3", size),
    Card('♠', "4", size),
    Card('♠', "5", size),
    Card('♠', "6", size),
    Card('♠', "7", size),
    Card('♠', "8", size),
    Card('♠', "9", size),
    Card('♠', "10", size),
    Card('♠', "J", size),
    Card('♠', "Q", size),
    Card('♠', "K", size),
    Card('♠', "A", size),
    //hearts
    Card('♥', "2", size),
    Card('♥', "3", size),
    Card('♥', "4", size),
    Card('♥', "5", size),
    Card('♥', "6", size),
    Card('♥', "7", size),
    Card('♥', "8", size),
    Card('♥', "9", size),
    Card('♥', "10", size),
    Card('♥', "J", size),
    Card('♥', "Q", size),
    Card('♥', "K", size),
    Card('♥', "A", size),
    //clubs
    Card('♣', "2", size),
    Card('♣', "3", size),
    Card('♣', "4", size),
    Card('♣', "5", size),
    Card('♣', "6", size),
    Card('♣', "7", size),
    Card('♣', "8", size),
    Card('♣', "9", size),
    Card('♣', "10", size),
    Card('♣', "J", size),
    Card('♣', "Q", size),
    Card('♣', "K", size),
    Card('♣', "A", size)
  )
}